---

- hosts: master
  gather_facts: yes
  become: yes

  # most vars are coming from 'group_vars/' directory
  vars:
    # version needed by more than one role (namespace labels)
    istio_version: 1.9.7 # validated on 1.7.5 and 1.9.7

    # 'false' means tested from inside master k3s-1
    istio_ingress_tested_from_localhost: false

  tasks:
  - name: run tests against istio gateways
    include_role:
      name: istio-gateway
      tasks_from: test.yml

