---

# Our own ubuntu prereq: os packages, settings, binaries
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - k3s-prereq

# roles coming from 'k3s-ansible' project
# https://github.com/k3s-io/k3s-ansible
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - prereq 
    - download

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    # /etc/rancher/k3s/config.yaml for k3s installation
    - k3s-initial-config
    # various utils
    - k9s
    - helm3
    - yq
