---

- hosts: master
  gather_facts: yes
  become: no
  tags:
    - ingress

  roles:
    # primary and secondary Daemonset nginx controllers
    - role: add_primary_nginx_ingress
    - role: add_secondary_nginx_ingress

    # Ingress objects
    - role: nginx-ingress
