---

- hosts: master
  become: yes
  roles:
    - { role: cert-with-ca, cert_overwrite: true }
    - { role: apply-k8s-tls-secrets, secret_namespace_list: [ 'default','istio-system' ], tls_secret_overwrite: true }
