---

# 
# originally, was getting manifest live from github, but needed to do some replacements
# including adding labels for prometheus scraping, so much easier to locally template
#
# OTHERWISE would have needed to use yq to modify the Deployment->Daemonset
# yq '. | select(.kind == "Deployment") | (.kind)="DaemonSet" | (.spec.template.metadata.labels) += {"prometheus.io/scrape":"true"} | (.spec.template.metadata.labels) += {"prometheus.io/port":"9093"}' nginx-deploy.yaml
#
# and then pull out the other part of the manifest unchanged
# yq '. | select(.kind != "Deployment")' nginx-deploy.yaml

#- name: get nginx ingress manifest
#  get_url:
#    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.0/deploy/static/provider/baremetal/deploy.yaml
#    dest: ./nginx-deploy.yaml
#    mode: '0666'
#
#- name: replace 'NodePort' with 'LoadBalancer'
#  replace:
#    path: ./nginx-deploy.yaml
#    regexp: '  type: NodePort'
#    replace: '  type: LoadBalancer'
#
#- name: replace 'Deployment' with 'DaemonSet'
#  replace:
#    path: ./nginx-deploy.yaml
#    regexp: 'kind: Deployment'
#    replace: 'kind: DaemonSet'

- name: copy older nginx ingress manifest template
  template:
    src: nginx-deploy-legacy.yaml
    dest: .
  when: k3s_major_minor_version < 'v1.22'

- name: copy nginx ingress v1.8.1 manifest template
  template:
    src: nginx-deploy-v1.8.1.yaml
    dest: nginx-deploy.yaml
  when: k3s_major_minor_version >= 'v1.22'

- name: apply nginx ingress manifest
  k8s:
    state: present
    #kubeconfig: "{{kubeconfig}}"
    src: ./nginx-deploy.yaml
