---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: lb.kubesphere.local:6443
    token: "gwwys0.28i5sges2w25vtw0"
    unsafeSkipCAVerification: true
  tlsBootstrapToken: "gwwys0.28i5sges2w25vtw0"
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 192.168.100.152
    bindPort: 6443
  certificateKey: b68cf183865d2bbb88eae7f686d7d3c4dd1bdfee32c79ac299f96b57d93ddcf7
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: cgroupfs
