---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: lb.kubesphere.local:6443
    token: "gwwys0.28i5sges2w25vtw0"
    unsafeSkipCAVerification: true
  tlsBootstrapToken: "gwwys0.28i5sges2w25vtw0"
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: cgroupfs
