---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: lb.kubesphere.local:6443
    token: "fz7bg7.vxtr4nmd1ovg51ot"
    unsafeSkipCAVerification: true
  tlsBootstrapToken: "fz7bg7.vxtr4nmd1ovg51ot"
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: cgroupfs
