---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: lb.kubesphere.local:6443
    token: "q3dqvk.642741hyp6nr81ap"
    unsafeSkipCAVerification: true
  tlsBootstrapToken: "q3dqvk.642741hyp6nr81ap"
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: cgroupfs
