
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: kubesphere-master-1, address: 192.168.122.151, internalAddress: 192.168.122.151, user: root, privateKeyPath: "/root/works/terraform-kb/kubesphere-libvirt/deploy/.ssh-default/id_rsa.key"}
  - {name: kubesphere-worker-1, address: 192.168.122.181, internalAddress: 192.168.122.181, user: root, privateKeyPath: "/root/works/terraform-kb/kubesphere-libvirt/deploy/.ssh-default/id_rsa.key"}
  roleGroups:
    etcd:
    - kubesphere-master-1
    control-plane: 
    - kubesphere-master-1
    worker:
    - kubesphere-master-1
    - kubesphere-worker-1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
