ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: mailhog.{{ cert_domains_list | first }}
      paths:
        - path: "/"
          pathType: Prefix

  tls:
  - secretName: {{secret_name}}
    hosts:
      - mailhog.{{ cert_domains_list | first }}

